### ISSUE TITLE
Connect to client if exists?

### ISSUE THREAD

**Issue by deven96** [jonhoo/fantoccini#111]
I'm curious as to whether it is possible to connect to an existing client if it has already been started somewhere rather than have `Client::new()` fail. Something like a `Client::new_or_connect()` that enables one to open a new window and do something else.

**Comment by jonhoo** [comment]
I think in theory that should be possible if you know the session ID. What use-case are you thinking of?

**Comment by deven96** [comment]
> I think in theory that should be possible if you know the session ID. What use-case are you thinking of?

I was thinking of an async web application that made use of fantocinni. Since only `Client::new` can be used and it fails when called elsewhere if there is a client already running, then exporting the session ID as an environmental variable and using that in `Client::new_or_connect()`

**Comment by jonhoo** [comment]
`Client::new` should not fail just because another session is already open. I believe this is only the case for `geckodriver`, and I believe it should be considered a bug there. Works fine with `chromedriver` for example (this is why the firefox tests in `fantoccini` all have `#[serial]`).

The challenge with `new_or_connect` is how you get the session ID of an existing session. I don't know if WebDriver provides an API endpoint to ask for current sessions — if it does, maybe we could use that? Otherwise, I think it'd have to be up to the application to re-use sessions by adding a `Client::from_session_id` where the application manually inputs the session ID that it already got from another `Client::new`. In either case you'll have to be a little careful about when you close the session though, since it may be being used by multiple `Clients`.

Another concern is that if you have multiple `Client`s connected through the same session, they are no longer independent, which may make them kind of useless. Imagine you have two tests that share a `Client`, and one tries to go to `foo.com` and the other `bar.com`. Since they are controlling the same browser session, the requests will end up racing with one another, and the browser will end up on one site or the other, not both.

**Comment by deven96** [comment]
Ah yes I see what you mean. The most appropriate function might be a `Client::from_session_id()`. About the racing requests, I think that would be up to the programmer to think about how to manage that, either by opening a new window or some other way

**Comment by jonhoo** [comment]
I'm going to close this in favor of https://github.com/jonhoo/fantoccini/issues/57
