### ISSUE TITLE
Implement `ElementSendKeys` command

### ISSUE THREAD

**Issue by Phrohdoh** [jonhoo/fantoccini#23]
https://docs.rs/webdriver/0.35.0/webdriver/command/enum.WebDriverCommand.html#variant.ElementSendKeys

### Questions / discussion points:

- Should we `click` the given `Element` for the user?
  - Can we determine if a given `Element` currently has focus?

- Where do we draw the line between implementing webdriver commands and building high-level abstractions?
  - Should these be two separate crates?

**Comment by Phrohdoh** [comment]
ref https://github.com/w3c/webdriver/issues/553

**Comment by Phrohdoh** [comment]
The state of webdriver implementations and `ElementSendKeys` is a bit of a mess.

See https://gist.github.com/Phrohdoh/8f4f7d1825221631dfc45c3ac6d3f9b8.

**Comment by jonhoo** [comment]
Some higher-level thoughts about this:

---

In general, I intended fantoccini to be a higher-level interface to browser automation. However, since no crate existed for the low-level bindings, it also provides those. It makes a lot of sense to split this into two crates (probably as subcrates of this repo given the tight integration), and then have the high-level crate use the low-level one. That way others can also take advantage of the low-level protocol implementation work we're doing to build their own (different) browser automation toolkits. I'd be happy to look at a PR that does this -- the divide should hopefully be pretty clear. We will likely want to expose the low-level interface *through* the high-level interface too so that users can fill in any gaps in the high-level easily themselves.

---

For places where the specs and implementations diverge, I am a strong proponent of following *just* the spec. This is a little weird with webdriver given that there's also sort of the old selenium spec, and you basically have to support that too. I'd prefer to stick to the spec when there's ambiguity though, because that's likely what the implementations will converge towards.

---

As for the specific question about `ElementSendKeys`, my first instinct is no. I'm imagining that `Element` will have a `.focus()` method which, well, focuses that element (through JS injection), and that `.send_keys()` will not implicitly call that or any other method. I *believe* that is the least surprising API design. We *could* also have a second method, `.type()`, which checks that the thing is editable, and if so, focuses it and sends the keys.
   - I think you can only determine focus with JS injection atm.

**Comment by jonhoo** [comment]
We have this now, right?

**Comment by Phrohdoh** [comment]
[Yep](https://github.com/jonhoo/fantoccini/blob/e3796cf4fe2f146bfe779b69bede280b84aa4a4e/src/lib.rs#L1046-L1060)!
