### ISSUE TITLE
Docs link broken

### ISSUE THREAD

**Issue by LeopoldArkham** [jonhoo/fantoccini#30]
Hey,

I'm looking at your crate for a project but the doc.rs link seems to be broken.
Since I'm here I may as well ask, would I be able to take screenshots using fantoccini? I know WebDriver supports it, does fantoccini cover all the WebDriver API?

Thanks!

**Comment by jonhoo** [comment]
Hi! Yeah, unfortunately this has been the case for a little while. It's because docs.rs isn't running Rust 1.26 yet, and therefore fails to compile `fantoccini` which now uses `impl Trait`. I've reported it [here](https://github.com/onur/docs.rs/issues/23#issuecomment-388968757), and hopefully it should be fixed in not too long :) You can always get to the docs by checking out the repository and running `cargo doc --open` though!

As for screenshots, we're in the process of adding that now! You should follow https://github.com/jonhoo/fantoccini/pull/29.

**Comment by LeopoldArkham** [comment]
Ok, thanks a lot!
