### ISSUE TITLE
chromedriver not respecting `--headless`

### ISSUE THREAD

**Issue by anp** [jonhoo/fantoccini#45]
Hi! Fantoccini has been exactly what I've needed so far. Thank you so much!

I'm trying to run chromedriver with the headless and disable-gpu arguments passed through the capabilities object, using both the documented `chromeOptions` flag and the `goog:chromeOptions` flag that current selenium seems to support. Here's the code I'm using to create the capabilities:

```rs
    let mut caps = serde_json::map::Map::new();
    let chrome_opts = serde_json::json!({ "args": ["--headless", "--disable-gpu"] });
    caps.insert("goog:chromeOptions".to_string(), chrome_opts.clone());
    caps.insert("chromeOptions".to_string(), chrome_opts);
```

Any advice on how to debug this? I've tried increasing log verbosity for fantoccini but haven't seen any messages come up.

**Comment by jonhoo** [comment]
Glad to hear you've found it useful! I'd also love to hear about any documentation shortcomings you may have come across so that we can improve things going forward! Documenting the use of `serde_json::json!` for capabilities for example would be a great addition.

As for the issue at hand, that's pretty weird. What happens if you run chromedriver with `--verbose`? Looking at the [Chrome docs](https://developers.google.com/web/updates/2017/04/headless-chrome#using_chromedriver), what you pass in should be sufficient. Looking at [this SO question](https://stackoverflow.com/questions/45130993/how-to-start-chromedriver-in-headless-mode#45131507), some people seem to be passing `headless` without `--`, and while that doesn't immediately make sense to me, it could be that that's necessary for some reason?

**Comment by jonhoo** [comment]
I think I found the issue! Should be fixed shortly in a new minor release :)

**Comment by anp** [comment]
Wonderful, tysm!

**Comment by petrstudynka** [comment]
For anyone who might with this struggle as I did, you need to add **browserName**, it won't process the args at all otherwise. Not sure if same applies for other browsers but my guess is, it does. I thought the driver can figure it on its own, but seems like it needs this "hint".

```rust
        let cap: Capabilities = serde_json::from_str(
            r#"{"browserName":"chrome","goog:chromeOptions":{"args":["--headless"]}}"#,
        )
        .unwrap();
        let driver = ClientBuilder::native()
            .capabilities(cap)
            .connect("http://127.0.0.1:4444")
            .await
            .expect("failed to connect to WebDriver");
```

Machine: x86 macOS Ventura 13.1 (22C65)
Driver: ChromeDriver 113.0.5672.63
