### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by palfrey** [jonhoo/fantoccini#72]
https://crates.io/crates/fantoccini has a "looking-for-maintainer" status. Is that still the case? Couldn't see an issue here talking about that or anything more in the README.

**Comment by jonhoo** [comment]
I'm still passively maintaining `fantoccini` for when there are PRs and issues, but I am not actively developing it even though I think there's probably good room for doing so. The fact that I am not actually using `fantoccini` for anything at the moment myself also doesn't help. Which is why I've marked the crate as looking for maintainers :)
