### ISSUE TITLE
Why do most methods use a mutable reference to Self?

### ISSUE THREAD

**Issue by ipkiss42** [jonhoo/fantoccini#86]
Methods such as `Client.find()` or `Element.attr()` currrently take `&'_ mut self` as first parameter.

This is unexpected, and doesn't seem necessary. For example, removing the `mut` from both `Client.find()` and `Client.issue()` compiles fine.

Having a mutable self prevents from sharing the reference, but sharing it is needed in various situations, such as using it in the closure of a stream:

```rust
use futures::stream::{self, Stream, StreamExt};
use fantoccini::Client;

async fn do_stuff_with_client(client: &Client) -> u8 {
    // Some code here
    0
}

fn create_stream(client: &Client) -> impl Stream<Item = u8> + '_ {
    stream::iter(0..10).then(move |i| do_stuff_with_client(client))
}

async fn main_async() {
    let client = Client::new("http://localhost:4444").await.unwrap();
    let mut stream = Box::pin(create_stream(&client));
    while let Some(value) = stream.next().await {
        println!("{}", &value);
    }
}
```

The above sample code does not compile anymore if the client reference is mutable.

So, why have mutable references all over your API? Would you consider removing them?

**Comment by jonhoo** [comment]
`Client` is `Clone` pretty much exactly so that you can clone the client handle if you wish. I don't want to make the methods take `&self` though, because, for example, it would mean that we are _required_ to use an unbounded channel here:
https://github.com/jonhoo/fantoccini/blob/93e849a8ca1b1eb1cb36b398eb425f2a23efb43c/src/session.rs#L22

Which I think we may want to move around from. It's also useful for the method to take `&mut self` just to remind the caller that they are mutating a single browser session. Arguably, `Client` shouldn't even be `Clone`, since the underlying webdriver connection handles requests one-at-a-time. But I decided that was too restrictive in practice.

**Comment by ipkiss42** [comment]
Thanks, having `Clone` is a nice workaround to get unblocked.

From an API perspective it seems inconsistent though: either it is unsafe to have multiple mutating clients, and then `Clone` should also be forbidden (which is very restrictive, as you point out), or it is not, and the API should reflect it without the need to clone.

> I don't want to make the methods take `&self` though, because, for example, it would mean that we are _required_ to use an unbounded channel here:
> 
> https://github.com/jonhoo/fantoccini/blob/93e849a8ca1b1eb1cb36b398eb425f2a23efb43c/src/session.rs#L22

I don't fully understand why an immutable reference would require an unbounded channel. However, it sounds like an implementation detail. I thought the usual way to handle this kind of use case is to use `RefCell`: https://doc.rust-lang.org/std/cell/index.html#implementation-details-of-logically-immutable-methods. But I am new to Rust and I have never used this class, so I may be missing something.

In any case, I am asking for my own education, not to be pushy. Feel free to resolve this issue if I didn't convince you or if I misunderstood something :)

**Comment by jonhoo** [comment]
I see your argument, although it doesn't quite hold because there is a subtle but important distinction between allowing concurrent calls via `&self` and via `Clone` + `&mut self`. They both allow you to issue requests "concurrently", but the former does not allow each call to have its own dedicated mutable state. More concretely, `UnboundedSender` has a `send(&self)`, but for example, `Sender` (the bounded version) only has a `send(&mut self)`. In general, `&mut self` allows you to "be smarter" about how you do that concurrency, since each handle can keep some dedicated per-handle state.

A `RefCell` would allow mutable access through a `&self`, but it would not allow _concurrent_ access, and it would make `Client` `!Sync`, which means it could not be shared among threads anyway, losing much of its benefit. We could use `Mutex` instead, though that also has some sad implications. An `mpsc` channel _seems_ like the right implementation detail here, which then basically requires us to go with `Clone` + `&mut self`.

Not sure if that helps? I'd be happy to explain further, but think we should close this as I don't think it's feasible to move to `&self`.

**Comment by ipkiss42** [comment]
Thank you for the explanation, it makes sense now.

I find it a bit scary that the public API gets "dictated" by low-level implementation details like that though.

**Comment by jonhoo** [comment]
I'm glad! :) I would think of it more this way: the API _should_ be just a single `Client` that takes `&mut self`. In almost all contexts, that should be sufficient. I believe even your example above could we rewritten to work with a single `Client` that takes `&mut self`. Because Rust's async/await/futures story is still a little wonky in the details, and the borrow checker is sometimes overly restrictive, it's useful to provide `Clone` as an escape-hatch. It is exactly that though — and escape hatch. In general, the user _should_ think of a `Client` as being a basically single-threaded thing that can just run one thing at a time, and `&mut self` reinforces that.

**Comment by ipkiss42** [comment]
> In general, the user should think of a `Client` as being a basically single-threaded thing that can just run one thing at a time

I thought more about this and I don't think this is true. Read-only operations, such as `current_url()`, `source()`, `find()`, etc have no reason to be executed sequentially, since they don't modify the page state (assuming the `Element`s are not used to mutate the page somehow).

The analogy with the borrow checker is striking: it should be allowed to do several read-only operations in parallel (just like it is fine to have multiple immutable references) OR one mutating operation (just like there can be only one mutable borrow at a time).

Here is a thought experiment: imagine that there were some hypothetical `PageState` struct stored in `Client` , which must be accessed by all the `Client` operations. Read-only operations would only need a regular reference (`&`), whereas mutating operations would require `&mut`, thus requiring that these operations take a `&mut self`. Let's also assume there is no `Element` struct to simplify. In such a situation, wouldn't you agree that this gives us the "right" API, both intuitive for users and automatically enforced by the borrow checker?

Assuming you agree with this, we could go back to the real world and keep this ideal API by using `&mut` only for mutating operations. It wouldn't be enforced by the borrow checker anymore, but it would still be nicer for users.

Unfortunately, it sounds like the implementation detail of `Sender::send()` taking `&mut self` would be incompatible. I'm not sure how to reconcile these two things (nicer API and implementation needs), but I would consider it as a language flaw if there was no way to reconcile them somehow.

What do you think? Do you agree with the nicer API I stated above? What would be the typical Rust way to reconcile it with the implementation details of the bounded queue?

**Comment by jonhoo** [comment]
Hmm, that's an interesting idea. It's definitely _possible_ (e.g., we could use a `Mutex`). I think if we wanted to go that route we should _not_ implement `Clone` though, otherwise the `&mut` wouldn't mean much. My guess is that what will happen then is that anyone who wants to use a `Client` across multiple threads then has to wrap it in `Arc<tokio::sync::Rw:Lock>`, which is a little unfortunate given that _internally_ we already have a nice way of sharing access (the channel).

What really makes this complicated is that while these operations are _logically_ concurrent, they still share a single _connection_ to the webdriver. That's where all these concerns around `&mut` are coming from. Even though some of the logical operations only "require" `&`, they _actually_ require `&mut` since they need to serialize access to the TCP channel to the webdriver. They aren't _fully_ independent.

As you have no doubt understood from the code at this point, the architecture is a little weird to accommodate the fact that this is how webdriver works. Instead of any given method call doing its own webdriver request, every method is really just a thin wrapper around a channel send. It wraps up the arguments to the method in a request to a singleton future that "drives" the connection, and issues one request at a time (since that's all webdriver supports as I understand it). Only when one request completes does it read the next request from the channel and issue that. Results are communicated back to the caller using oneshot channels that are sent with the requests.

I think it's worthwhile to try out an API that gives _true_ mutability signatures for `Client`. That is, `current_url` would take `&self`, while `goto` would take `&mut self`. Under the hood, of course, they all mutate shared state, but that (I think) can be isolated to the singleton driver. It would mean we'd have to stick to an unbounded channel, but that may be worth the trade-off, especially since this is not a very performance sensitive use-case.

**Comment by jonhoo** [comment]
Where this also gets complicated is in cases like with `Element`. `Client::find` should presumably only take `&self`. But `Element::click` should (presumably) require an exclusive reference to the `Client`. I'm not entirely sure how we achieve that.
