### ISSUE TITLE
Can't wait_for operations other than find and navigate

### ISSUE THREAD

**Issue by Vypo** [jonhoo/fantoccini#90]
Like I mentioned in my pull request, if elements exist in the DOM, but are hidden with CSS, operations like `click` will fail. I have a [working example][0], but the short form of my current workaround is:

```html
<!DOCTYPE html>
<html>
<body>
<a style="display: none;">foo</a>
<script>
setTimeout(() => {
let a = document.getElementsByTagName('a')[0];
a.style.display = 'block';
}, 30000);
</script>
</body>
</html>
```

```rust
let elem = client.find(Locator::Css("a")).await?;

while elem.clone().click().await.is_err() {
    std::thread::sleep(std::time::Duration::from_secs(1));
}
```

[0]: https://github.com/Vypo/fantoccini-example/blob/master/src/main.rs

**Comment by jonhoo** [comment]
Thank you for the minimal example, that helps! This sort of ties into the discussion over in #86 — if `click` took `&mut self` instead of `self`, then the `clone` there wouldn't be necessary, and everything would "just work". That would also make it possible to write this using `wait_for`, since `&mut Client` would then (I believe) be sufficient.
